spring.application.name=hr-cms

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.cache.host=${REDIS_HOST}
spring.cache.port=${REDIS_PORT}
spring.cache.username=${REDIS_USERNAME}
spring.cache.password=${REDIS_PASSWORD}