spring.application.name=hr-cms

spring.datasource.url=jdbc:postgresql://localhost:6032/DATABASE
spring.datasource.username=KENNA
spring.datasource.password=WACHTWOORD
server.port=6033
spring.thymeleaf.cache=false