name: "hard-work"

services:
  server:
    container_name: hard-work-server
    env_file: ".env"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: hr-cms-server
    ports:
      - "6031:${SERVER_PORT}"
    depends_on:
      db_postgres:
        condition: service_healthy
      cache_redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    mem_limit: 500mb
    cpus: 1
    volumes:
      - uploads:/app/uploads/media

  db_postgres:
    image: postgres:18.2-trixie
    container_name: hard-work-postgres
    env_file: ".env"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      CMS_FLYWAY_PASSWORD: ${CMS_FLYWAY_PASSWORD}
      CMS_SUPERUSER_PASSWORD: ${CMS_SUPERUSER_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./hr-cms/src/main/resources/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "6032:5432" # Currently exposed. Should be removed for a production environment.
    mem_limit: 2g
    cpus: 1

  mongo:
    image: mongo:7
    container_name: mongo_db
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cache_redis:
    image: redis/redis-stack:7.4.0-v8
    container_name: hard-work-redis
    env_file: ".env"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} "
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -p ${REDIS_PORT} -a $$REDIS_PASSWORD ping" ]
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

    mem_limit: 100mb
    cpus: 1

  neo4j:
    image: neo4j:2026.04.0-trixie
    container_name: hard-work-neo4j
    env_file: ".env"
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_dbms_memory_heap_initial__size: 256m
      NEO4J_dbms_memory_heap_max__size: 256m
      NEO4J_dbms_memory_pagecache_size: 256m
    volumes:
      - neo4jdata:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -a bolt://localhost:7687 -u neo4j -p \"$$SPRING_NEO4J_AUTHENTICATION_PASSWORD\" 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt protocol (application communication)
    mem_limit: 1g
    cpus: 1

volumes:
  pgdata:
  uploads:
  mongo_data:
  neo4jdata:
