name: "hard-work"
services:
# Server has been copied from private project and can serve as template for later on
  server:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    image: hr-cms-server
    ports:
      - "6031:8080"
    depends_on:
      db:
        condition: service_healthy
    mem_limit: "500mb"
    cpus: "1"
    network_mode: "host"

  db:
    container_name: hard-work-postgres
    env_file: ".env"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DATABASE}", "-U", "${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "6032:5432"
    expose:
      - 6032

    mem_limit: "2g"
    cpus: "1"

volumes:
  pgdata:
